# Generated by Django 4.2.16 on 2024-11-23 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mathces', to='general.event'),
        ),
    ]
