# Generated by Django 4.2.16 on 2024-11-23 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_remove_event_description_event_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
    ]
